// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 105549438319484129),
    name: 'CategoryEntity',
    lastPropertyId: const obx_int.IdUid(13, 2086119464170389808),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5760706068875535829),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1513122581892072364),
        name: 'cloudId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 5604622927574249279),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1796045059409752364),
        name: 'slug',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4536149654404083280),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 691227488143775762),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4655297118937412373),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5049989882870042852),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9175222402264558405),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5518099306752028082),
        name: 'isSystem',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5093915919609929250),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6529370800636351979),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 420892746569175079),
        name: 'parentLocalId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8439901810132768216),
        name: 'parentCloudId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 3242001642591307251),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2086119464170389808),
        name: 'depth',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 547014499566678480),
    name: 'ItemEntity',
    lastPropertyId: const obx_int.IdUid(16, 5738298030483930867),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2660392381277599372),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1006931783331665950),
        name: 'cloudId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 3496195649179787487),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8167489757199002034),
        name: 'categoryLocalId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8826563589633552540),
        name: 'categoryCloudId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 2649101114840178317),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9098688877727754402),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6635935754173735473),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3478412980109392082),
        name: 'localImagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8956607395157935637),
        name: 'cloudFileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6663287002992834315),
        name: 'cloudPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5822852782192910593),
        name: 'tagsRaw',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1670630005579267771),
        name: 'syncStatusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2276465013998826599),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8252711589691449830),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5564536466170909697),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5143609040347936284),
        name: 'colorsRaw',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5738298030483930867),
        name: 'colors',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 547014499566678480),
    lastIndexId: const obx_int.IdUid(5, 3242001642591307251),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryEntity: obx_int.EntityDefinition<CategoryEntity>(
      model: _entities[0],
      toOneRelations: (CategoryEntity object) => [],
      toManyRelations: (CategoryEntity object) => {},
      getId: (CategoryEntity object) => object.id,
      setId: (CategoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryEntity object, fb.Builder fbb) {
        final cloudIdOffset = fbb.writeString(object.cloudId);
        final slugOffset = fbb.writeString(object.slug);
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        final colorOffset = fbb.writeString(object.color);
        final parentCloudIdOffset = fbb.writeString(object.parentCloudId);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cloudIdOffset);
        fbb.addOffset(2, slugOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, iconOffset);
        fbb.addOffset(5, colorOffset);
        fbb.addInt64(6, object.sortOrder);
        fbb.addBool(7, object.isSystem);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.parentLocalId);
        fbb.addOffset(11, parentCloudIdOffset);
        fbb.addInt64(12, object.depth);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CategoryEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..cloudId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..slug = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..icon = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..color = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..sortOrder = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..isSystem = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
          )
          ..parentLocalId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..parentCloudId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..depth = const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);

        return object;
      },
    ),
    ItemEntity: obx_int.EntityDefinition<ItemEntity>(
      model: _entities[1],
      toOneRelations: (ItemEntity object) => [],
      toManyRelations: (ItemEntity object) => {},
      getId: (ItemEntity object) => object.id,
      setId: (ItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ItemEntity object, fb.Builder fbb) {
        final cloudIdOffset = fbb.writeString(object.cloudId);
        final categoryCloudIdOffset = fbb.writeString(object.categoryCloudId);
        final titleOffset = fbb.writeString(object.title);
        final noteOffset = fbb.writeString(object.note);
        final localImagePathOffset = fbb.writeString(object.localImagePath);
        final cloudFileIdOffset = fbb.writeString(object.cloudFileId);
        final cloudPathOffset = fbb.writeString(object.cloudPath);
        final tagsRawOffset = fbb.writeString(object.tagsRaw);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final colorsRawOffset = fbb.writeString(object.colorsRaw);
        final colorsOffset = fbb.writeList(
          object.colors.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cloudIdOffset);
        fbb.addInt64(2, object.categoryLocalId);
        fbb.addOffset(3, categoryCloudIdOffset);
        fbb.addOffset(4, titleOffset);
        fbb.addOffset(5, noteOffset);
        fbb.addOffset(6, localImagePathOffset);
        fbb.addOffset(7, cloudFileIdOffset);
        fbb.addOffset(8, cloudPathOffset);
        fbb.addOffset(9, tagsRawOffset);
        fbb.addInt64(10, object.syncStatusIndex);
        fbb.addInt64(11, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(12, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(13, tagsOffset);
        fbb.addOffset(14, colorsRawOffset);
        fbb.addOffset(15, colorsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ItemEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..cloudId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..categoryLocalId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..categoryCloudId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..title = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..note = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..localImagePath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..cloudFileId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..cloudPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..tagsRaw = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..syncStatusIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
          )
          ..tags = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 30, [])
          ..colorsRaw = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 32, '')
          ..colors = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 34, []);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryEntity] entity fields to define ObjectBox queries.
class CategoryEntity_ {
  /// See [CategoryEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[0],
  );

  /// See [CategoryEntity.cloudId].
  static final cloudId = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[1],
  );

  /// See [CategoryEntity.slug].
  static final slug = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[2],
  );

  /// See [CategoryEntity.name].
  static final name = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[3],
  );

  /// See [CategoryEntity.icon].
  static final icon = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[4],
  );

  /// See [CategoryEntity.color].
  static final color = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[5],
  );

  /// See [CategoryEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[6],
  );

  /// See [CategoryEntity.isSystem].
  static final isSystem = obx.QueryBooleanProperty<CategoryEntity>(
    _entities[0].properties[7],
  );

  /// See [CategoryEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<CategoryEntity>(
    _entities[0].properties[8],
  );

  /// See [CategoryEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<CategoryEntity>(
    _entities[0].properties[9],
  );

  /// See [CategoryEntity.parentLocalId].
  static final parentLocalId = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[10],
  );

  /// See [CategoryEntity.parentCloudId].
  static final parentCloudId = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[11],
  );

  /// See [CategoryEntity.depth].
  static final depth = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[12],
  );
}

/// [ItemEntity] entity fields to define ObjectBox queries.
class ItemEntity_ {
  /// See [ItemEntity.id].
  static final id = obx.QueryIntegerProperty<ItemEntity>(
    _entities[1].properties[0],
  );

  /// See [ItemEntity.cloudId].
  static final cloudId = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[1],
  );

  /// See [ItemEntity.categoryLocalId].
  static final categoryLocalId = obx.QueryIntegerProperty<ItemEntity>(
    _entities[1].properties[2],
  );

  /// See [ItemEntity.categoryCloudId].
  static final categoryCloudId = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[3],
  );

  /// See [ItemEntity.title].
  static final title = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[4],
  );

  /// See [ItemEntity.note].
  static final note = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[5],
  );

  /// See [ItemEntity.localImagePath].
  static final localImagePath = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[6],
  );

  /// See [ItemEntity.cloudFileId].
  static final cloudFileId = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[7],
  );

  /// See [ItemEntity.cloudPath].
  static final cloudPath = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[8],
  );

  /// See [ItemEntity.tagsRaw].
  static final tagsRaw = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[9],
  );

  /// See [ItemEntity.syncStatusIndex].
  static final syncStatusIndex = obx.QueryIntegerProperty<ItemEntity>(
    _entities[1].properties[10],
  );

  /// See [ItemEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ItemEntity>(
    _entities[1].properties[11],
  );

  /// See [ItemEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ItemEntity>(
    _entities[1].properties[12],
  );

  /// See [ItemEntity.tags].
  static final tags = obx.QueryStringVectorProperty<ItemEntity>(
    _entities[1].properties[13],
  );

  /// See [ItemEntity.colorsRaw].
  static final colorsRaw = obx.QueryStringProperty<ItemEntity>(
    _entities[1].properties[14],
  );

  /// See [ItemEntity.colors].
  static final colors = obx.QueryStringVectorProperty<ItemEntity>(
    _entities[1].properties[15],
  );
}
